### ISSUE TITLE
UI won't close!

### ISSUE THREAD

**Issue by dixieland-gaming** [MamBa-OP/mb-inventory#1]
UI won't close! If you open the inventory and try to close it, the UI will not close! Only when you restart the script does the UI close until it is called again!

**Comment by dixieland-gaming** [comment]
in app.js 
qb-inventory to MB-Inventory and the UI closes ;)

**Comment by MamBa-OP** [comment]
at first rename it to qb-inventory then if it still not work then replace any the CSS, js with the latest lj-inventory
